### ISSUE TITLE
Regarding the obstacle

### ISSUE THREAD

**Issue by victorkhoo** [ybmasmiling/Astar_3D#1]
Hi @ybmasmiling,

Your code really help me to alot. Thanks ! 
But may I know how to put the cylinders as an obstacle in the plot? I tried understanding and edit the makedata.m. I understand how you make the terrain map, but I don't understand where to edit to change the cylinder(obstacle) position on the map. I noticed inside the CLOSED variables, it has additional elements after X=100 and Y=100, why the algorithm time increase when I remove those elements?  What is the purpose for the additional elements inside CLOSED ?

**Comment by ybmasmiling** [comment]
Hi, there are two kinds of terrain points in the CLOSED, one is the terrain data, the other is the cylinder data, I make the terrain data and cylinder data is -1, in fact, they are treated the same way. When you remove those elements, the planning space is bigger, the time is longer.
